name: Build Docker Images
on:
  push:
    branches:
      - main

env:
  POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE }}
  POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
  POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECR_PRODUCTION_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          WEB: laravel-docker-production-app
          QUEUE_WORKER: laravel-docker-production-queue-worker
        run: |
          docker compose build
          docker image ls
